<a href="https://colab.research.google.com/github/samuel-mati/Introduction-to-Pytorch/blob/main/Introduction_to_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**


*   A **torch.Tensor** is a multi-dimensional matrix containing elements of a single datatype.
*   Similar to Numpy Arrays, but full of fun things to make them work better on GPU's
*  Default data type of float32
*  More suitable for deep learning than numpy array




In [2]:
import torch
import numpy as np

## **LISTS**

In [3]:
 my_list=[[1,2,3,4,5],[6,7,8,9,10]]
 my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

### **NUMPY ARRAYS**

In [4]:
np1=np.random.rand(3,4)
np1

array([[0.42700619, 0.31577618, 0.57183397, 0.42529429],
       [0.13011096, 0.43420209, 0.22695529, 0.9240136 ],
       [0.45523978, 0.51680264, 0.77646693, 0.57838836]])

In [5]:
np1.dtype

dtype('float64')

### **TENSORS**

In [6]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[-1.4858e+00,  1.0158e+00,  1.2603e+00,  1.4249e+00],
        [ 7.8176e-01, -3.4261e-01,  1.7223e-01, -1.2030e+00],
        [-1.9170e+00, -1.0863e-03,  1.8560e-01, -3.5176e-01]])

In [10]:
tensor_3d=torch.zeros(2,3,4)
tensor_3d
#tensor_3d.dtype

torch.float32

In [9]:
## Create a tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.4270, 0.3158, 0.5718, 0.4253],
        [0.1301, 0.4342, 0.2270, 0.9240],
        [0.4552, 0.5168, 0.7765, 0.5784]], dtype=torch.float64)

## **Tensor Operations**

In [11]:
my_torch=torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#Reshape and View

my_torch=my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
#Reshape if we dont know the number of items
my_torch2=torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
my_torch2=my_torch2.reshape(5,-1)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [19]:
my_torch3=torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch4=my_torch3.view(2,-1)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

Both `reshape` and `view` are used to change the shape of a tensor. However, there are some key differences.

**view**

Returns a view of the original tensor: This means that the new tensor shares the same underlying data as the original tensor. Any changes made to the view will be reflected in the original tensor, and vice versa.
Requires the tensor to be contiguous: A contiguous tensor is one whose elements are stored in a contiguous block of memory. If the tensor is not contiguous, view will raise an error. You can use `torch.contiguous()` to make a tensor contiguous.
Generally faster than reshape: Since view does not copy the data, it is usually faster than reshape.


**reshape**

May return a copy or a view of the original tensor: If the new shape is compatible with the original tensor's memory layout, reshape will return a view. Otherwise, it will return a copy. This behavior is not guaranteed, and it may change in future PyTorch versions.
Can handle non-contiguous tensors: Unlike view, reshape can handle non-contiguous tensors. It will automatically copy the data if necessary.
May be slower than view: Since reshape may need to copy the data, it can be slower than view.

**In summary:**

If you need a view of the original tensor and the tensor is contiguous, use view.
If you need to change the shape of a non-contiguous tensor, or if you don't care whether the new tensor is a view or a copy, use reshape.
If you need a copy of the tensor with a new shape, use` clone()` followed by `reshape()`
In the context of your code:

Both reshape and view are used to change the shape of the tensors my_torch, my_torch2, and my_torch3. Since these tensors are contiguous, both methods will return a view of the original tensor. Therefore, in this case, there is no practical difference between using reshape and view.

In [21]:
# with reshape and view they will update

my_torch5=torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
my_torch5[1]=5000
my_torch5

tensor([   0, 5000,    2,    3,    4,    5,    6,    7,    8,    9])

In [27]:
my_torch6
#the value at [1] has been updated

tensor([[   0, 5000,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [28]:
#Slices

my_torch7=torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#Graba specific item
my_torch7[7]

tensor(7)

In [30]:
#Grab Slices
my_torch8=my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [31]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [32]:
#return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## **TENSOR MATH OPERATIONS**

In [35]:
tensor_a=torch.tensor([1,2,3,4])
tensor_b=torch.tensor([5,6,7,8])


In [36]:
#Addition
tensor_a+tensor_b

tensor([ 6,  8, 10, 12])

In [37]:
#Tensor Addition Long hand

torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [41]:
#Subtraction
tensor_b-tensor_a

# torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [42]:
#Multiply
#tensor_a*tensor_b

torch.multiply(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [44]:
#Divsion

#tensor_a/tensor_b

torch.div(tensor_a,tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [46]:
#Modular

tensor_b%tensor_a

#torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [49]:
#Exponents/Power

#tensor_a**tensor_b

#torch.pow(tensor_a,tensor_b)

tensor_a.pow(tensor_b)

tensor([    1,    64,  2187, 65536])

In [50]:
#Reassignment

#tensor_a+=tensor_b
#tensor_a
tensor_a=tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])